# springboot 端口号
server:
  port: 8113
# 应用名称
spring:
  application:
    name: demo
# 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.230.44:3306/chatroom?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "c93c83e1178aa08e"
    druid:
      test-on-borrow: true
      test-while-idle: true
  # Redis配置
  redis:
    # Redis 服务器地址
    host: 152.136.230.44
    # 连接端口号
    port: 6379
    # 密码
    password: Winner99,,
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0
  cache:
    type: redis
#  profiles:
#    active: prod

logging:
  level:
    root: info

file:
  ip: 152.136.230.44
  path: /www/wwwroot/album.moumangtai.com/img/