server:
  port: 8113

spring:
  # 数据库相关
  datasource:
    url: jdbc:mysql://152.136.230.44:3306/chatroom?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: chatRoom
    password: 7KSmK542SzbJfJyy
  redis:
    # Redis 服务器地址
    host: 127.0.0.1
    # 连接端口号
    port: 6379
    # 密码
    password: Winner99,,


file:
  ip: 152.136.230.44